apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ksqldb.fullname" . }}
  labels:
    {{- include "ksqldb.labels" . | nindent 4 }}
  annotations:
{{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.tlsSecretName | default "nginx" }}
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ingress.url }}
    secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "ksqldb.fullname" . }}
            port:
              number: {{ .Values.port }}