apiVersion: v1
kind: Service
metadata:
  name: {{ include "ksqldb.fullname" . }}
  labels:
    {{- include "ksqldb.labels" . | nindent 4 }}
spec:
{{- if .Values.service.clusterIp  }}
  type: ClusterIP
{{- else if .Values.service.LoadBalancer }}
  type: LoadBalancer
{{- end }}
  ports:
  - name: tcp
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: tcp
  selector:
    {{- include "ksqldb.selectorLabels" . | nindent 4 }}
