apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: kafka-internal
    port: {{ .Values.port.kafkaInternal }}
    protocol: TCP
    targetPort: kafka-internal
  - name: kafka-external
    port: {{ .Values.port.kafkaExternal }}
    protocol: TCP
    targetPort: kafka-external
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
