apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kafka.fullname" . }}-pdb
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "kafka.selectorLabels" . | nindent 6 }}