apiVersion: v1
kind: Service
metadata:
  name: {{ include "schema-registry-ui.fullname" . }}
  labels:
    {{- include "schema-registry-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: tcp
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: tcp
{{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{.Values.service.nodePort}}
{{ end }}
  selector:
    {{- include "schema-registry-ui.selectorLabels" . | nindent 4 }}
