apiVersion: v2
appVersion: 7.3.0
description: A Helm chart for Confluent Kafka Connect on Kubernetes
home: https://github.com/AHPanna/helm-charts
icon: https://svn.apache.org/repos/asf/comdev/project-logos/originals/kafka.svg
keywords:
- kafka
- kafka-connect
- confluent
maintainers:
- name: Panna ABDUL HAKIM
  email: ahpanna96gmail.com
  url: https://github.com/AHPanna
name: kafka-connect
sources:
- https://github.com/AHPanna/helm-charts
- https://github.com/ricardo-aires/helm-charts
- https://docs.confluent.io/platform/current/connect/index.html
type: application
version: 0.2.0
